
const alcoholData = [
    {
        id: 'L01',
        name: 'vodka',
        ethanol: 16,
        calories: 64,
        fat: 0,
        carb: 0,
        sugar: 0,
        addedSugar: 0,
        protein: 0,
        proof: 80,
    },
    {
        id: 'L02',
        name: 'rum',
        ethanol: 16,
        calories: 64,
        fat: 0,
        carb: 0,
        sugar: 0,
        addedSugar: 0,
        protein: 0,
        proof: 80,
    },
    {  
        id: 'L03',
        name: 'gin',
        ethanol: 16,
        calories: 64,
        fat: 0,
        carb: 0,
        sugar: 0,
        addedSugar: 0,
        protein: 0,
        proof: 80,
    },
    {
        id: 'L04',
        name: 'tequila',
        ethanol: 16,
        calories: 64,
        fat: 0,
        carb: 0,
        sugar: 0,
        addedSugar: 0,
        protein: 0,
        proof: 80,
    },
    {
        id: 'L05',
        name: 'whiskey',
        ethanol: 17.5,
        calories: 72,
        fat: 0,
        carb: 0.5,
        sugar: .03,
        addedSugar: 0,
        protein: 0,
        proof: 86,
    },
    {
        id: 'L06',
        name: 'cognac',
        ethanol: 10,
        calories: 68,
        fat: 0,
        carb: 7,
        sugar: 2,
        addedSugar: 2,
        protein: 0,
        proof: 80,
    },
    {
        id: 'L07',
        name: 'red wine',
        ethanol: 4,
        calories: 25,
        fat: 0,
        carb: 2,
        sugar: 0,
        addedSugar: 0,
        protein: 0,
        proof: 30,
    },
    {
        id: 'C01',
        name: 'triple sec',
        ethanol: 16.5,
        calories: 94,
        fat: 0,
        carb: 7,
        sugar: 7,
        addedSugar: 3,
        protein: 0,
        proof: 80,
        
    },
    {
        id: 'C02',
        name: 'kahlua',
        ethanol: 4.68,
        calories: 80,
        fat: 0,
        carb: 11.88,
        sugar: 11.88,
        addedSugar: 11.88,
        protein: 0,
        proof: 40,
        
    },
    {
        id: 'C03',
        name: 'peach schnapps',
        ethanol: 5.55,
        calories: 51,
        fat: 0,
        carb: 7.2,
        sugar: 7.2,
        addedSugar: 7.2,
        protein: 0,
        proof: 30,
        
    },
    {
        id: 'C04',
        name: 'frangelico',
        ethanol: 3.2,
        calories: 62,
        fat: 0,
        carb: 12.3,
        sugar: 11,
        addedSugar: 11,
        protein: 0,
        proof: 30,
    },
    {
        id: 'C05',
        name: 'limoncello',
        ethanol: 6.4,
        calories: 72.8,
        fat: 0,
        carb: 11.8,
        sugar: 11.7,
        addedSugar: 11.7,
        protein: 0,
        proof: 52,
    },
    
    {
        id: 'C06',
        name: 'amaretto',
        ethanol: 6.5,
        calories: 94,
        fat: 0,
        carb: 17,
        sugar: 11,
        addedSugar: 11,
        protein: 0,
        proof: 56,
        
    },
    {
        id: 'C07',
        name: 'benedictine',
        ethanol: 9.23,
        calories: 72,
        fat: 0,
        carb: 8.67,
        sugar: 5,
        addedSugar: 5,
        protein: 0.1,
        proof: 80,
        
    },
    {
        id: 'C08',
        name: 'jagermeister',
        ethanol: 8,
        calories: 74,
        fat: 0,
        carb: 10.5,
        sugar: 5,
        addedSugar: 5,
        protein: 0,
        proof: 70,
        
    },
    {
        id: 'C09',
        name: 'midori',
        ethanol: 4.67,
        calories: 74,
        fat: 0,
        carb: 13.33,
        sugar: 11,
        addedSugar: 11,
        protein: 0.5,
        proof: 40,
        
    },
    {
        id: 'C10',
        name: 'grand marnier',
        ethanol: 9,
        calories: 76,
        fat: 0,
        carb: 10,
        sugar: 2,
        addedSugar: 2,
        protein: 0,
        proof: 80,
        
    },

    {
        id: 'J01',
        name: 'lime',
        ethanol: 0,
        calories: 10.4,
        fat: 0,
        carb: 2.6,
        sugar: 0.5,
        addedSugar: 0,
        protein: 0.1,
        proof: 0,
    },
    {
        id: 'J02',
        name: 'lemon',
        ethanol: 0,
        calories: 10.4,
        fat: 0,
        carb: 2.6,
        sugar: 0.73,
        addedSugar: 0,
        protein: 0,
        proof: 0,
    },
    {
        id: 'J03',
        name: 'cranberry',
        ethanol: 0,
        calories: 17,
        fat: 0.03,
        carb: 4.27,
        sugar: 3.75,
        addedSugar: 3.75,
        protein: 0,
        proof: 0,
    },
    {
        id: 'J04',
        name: 'pineapple',
        ethanol: 0,
        calories: 17,
        fat: 0.04,
        carb: 4.02,
        sugar: 3.11,
        addedSugar: 0,
        protein: 0,
        proof: 0,
    },
    {
        id: 'J05',
        name: 'orange',
        ethanol: 0,
        calories: 14,
        fat: 0.06,
        carb: 3.22,
        sugar: 2.6,
        addedSugar: 0,
        protein: 0,
        proof: 0,
    },
    {
        id: 'J06',
        name: 'egg white',
        ethanol: 0,
        calories: 8,
        fat: 0,
        carb: 0,
        sugar: 0,
        addedSugar: 0,
        protein: 0,
        proof: 1.7,
    },
    {
        id: 'S01',
        name: 'simple syrup',
        ethanol: 0,
        calories: 52,
        fat: 0,
        carb: 13,
        sugar: 13,
        addedSugar: 13,
        protein: 0,
        proof: 0,
    },
    {
        id: 'S02',
        name: 'agave syrup',
        ethanol: 0,
        calories: 120,
        fat: 0,
        carb: 32,
        sugar: 32,
        addedSugar: 0,
        protein: 0,
        proof: 0,
    },
]
export {alcoholData}