
const alcoholData = [
    {
        name: 'vodka',
        fat: 0,
        carb: 0,
        sugar: 0,
        protein: 0,
        calories: 64,
        proof: 80,
        ethanol: 9.14,
    },
    {
        name: 'rum',
        id: 3,
        fat: 0,
        carb: 0,
        sugar: 0,
        protein: 0,
        calories: 64,
        proof: 80,
        ethanol: 9.14,
    },
    {  
        name: 'gin',
        fat: 0,
        carb: 0,
        sugar: 0,
        protein: 0,
        calories: 64,
        proof: 80,
        ethanol: 9.14,
    },
    {
        name: 'tequila',
    },
    {
        name: 'whiskey',
        fat: 0,
        carb: 0.3,
        sugar: .03,
        protein: 0,
        calories: 71,
        proof: 86,
        ethanol: 10,
    },
    {
        name: 'triple sec',
        fat: 0,
        carb: 7,
        sugar: 7,
        addedSugar: 3,
        protein: 0,
        calories: 95,
        proof: 80,
        ethanol: 9.5,
    },
    {
        name: 'lime',
        fat: 0,
        carb: 2.6,
        sugar: 0.5,
        addedSugar: 0,
        protein: 0.1,
        calories: 10.4,
    },
    {
        name: 'lemon',
        fat: 0,
        carb: 2.6,
        sugar: 0.73,
        addedSugar: 0,
        protein: 0,
        calories: 10.4,
    },
    {
        name: 'cranberry',
        fat: 0.03,
        carb: 4.27,
        sugar: 3.75,
        addedSugar: 3.75,
        protein: 0,
        calories: 17,
    },
    {
        name: 'pineapple',
        fat: 0.04,
        carb: 4.02,
        sugar: 3.11,
        addedSugar: 0,
        protein: 0,
        calories: 17,
    },
    {
        name: 'orange',
        fat: 0.06,
        carb: 3.22,
        sugar: 2.6,
        addedSugar: 0,
        protein: 0,
        calories: 14,
    },
    {
        name: 'simple',
        fat: 0,
        carb: 0,
        sugar: 13,
        addedSugar: 13,
        protein: 0,
        calories: 52,
    },
]
export {alcoholData}